$(document).ready(function(){
    document.getElementById('loading').innerHTML='Done!';
    setTimeout(function(){
        $("#loading").css("opacity","0");
        $("#bigtext").css("left","0");
    },200)
    setTimeout(function(){
        $("header").css("top","0px");
    },400)
    setTimeout(function(){
        $("#loading").css("display","none");
    },1000)
});